### ISSUE TITLE
Newer minecraft versions aren't added

### ISSUE THREAD

**Issue by qewrwer23qf** [AppleMacOS/Scripts#2]
in https://github.com/AppleMacOS/Scripts/blob/main/Minecraft-Scripts/vanilla-server.sh in how it gets its versions. i noticed its missing 1.17+ & 1.8-

**Comment by AppleMacOS** [comment]
I don't quite understand what you mean. It has everything from 1.7.2 to 1.17.1 (which is the latest version)

**Comment by qewrwer23qf** [comment]
look into the vanilla-server json it looks at.

**Comment by AppleMacOS** [comment]
Oh right, I see what you mean now. I forgot that whenever you edited a GitHub Gist that it would generate a new hash for the new version.

Thanks for letting me know 😀
